[package]
name = "ray-tracing"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
threadpool = "1.7.0"
num_cpus = "1.10.0"
image = "0.21.0"
